import { generate } from "@graphql-codegen/cli";
import { Injectable } from "@nestjs/common";
import {
  HasuraInstanceOptions,
  NamedHasuraInstanceOptions,
} from "./hasura.module-options";
import { HasuraService } from "./hasura.service";

/**
 * Service for managing code generation for a specific Hasura instance
 */
@Injectable()
export class HasuraCodegenService {
  constructor(
    private readonly hasuraInstanceOptions:
      | HasuraInstanceOptions
      | NamedHasuraInstanceOptions
  ) {}

  /**
   * Wraps `generate` from `@graphql-codegen/cli`, buildling configuration from injected instance options
   */
  async graphqlCodegen(): Promise<void> {
    await generate({
      schema: {
        [HasuraService.hasuraGraphqlUrl(this.hasuraInstanceOptions)]: {
          headers: {
            [HasuraService.hasuraAdminSecretHeader(
              this.hasuraInstanceOptions
            )]: this.hasuraInstanceOptions.adminSecret,
          },
        },
      },
      documents: this.buildDocumentsGlob(),
      overwrite: true,
      generates: {
        [this.generatedFile()]: {
          plugins: [
            "typescript",
            "typescript-operations",
            "typescript-graphql-request",
          ],
        },
      },
    });
  }

  /**
   * Computes the path of the file to be generated by codegen, given injected instance options
   */
  generatedFile(): string {
    let path = `src/${
      this.hasuraInstanceOptions.sdkOptions?.codegen?.outputDir ??
      HasuraCodegenService.DEFAULT_OUTPUT_ROOT
    }`;
    if ("name" in this.hasuraInstanceOptions) {
      path = `${path}/${this.hasuraInstanceOptions.name}`;
    }

    return `${path}/graphql.ts`;
  }

  /**
   * Builds glob string for finding GraphQL Schema, given provided configuration for injected Hasura instance
   */
  buildDocumentsGlob(): string {
    let base = "src/**/";
    if ("name" in this.hasuraInstanceOptions) {
      return base + `*.${this.hasuraInstanceOptions.name}.graphql`;
    }

    return base + "*.graphql";
  }

  static DEFAULT_OUTPUT_ROOT = "hasura-codegen";
}
